export function downloadBookingPDF(receipt, txHashOverride = null) {
  if (typeof window === 'undefined' || !window.jspdf) {
    alert('PDF not available. Try JSON download.')
    return
  }
  const { jsPDF } = window.jspdf
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const margin = 20
  let y = margin

  const addField = (key, value) => {
    doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(100,100,100)
    doc.text(key, margin, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(17,17,17)
    const lines = doc.splitTextToSize(value || '—', 130)
    doc.text(lines, 70, y)
    y += Math.max(lines.length * 5, 7)
  }
  const addDivider = () => {
    doc.setDrawColor(220,220,220); doc.line(margin, y, 190, y); y += 5
  }

  // Header
  doc.setFillColor(17,17,17); doc.rect(0,0,210,25,'F')
  doc.setFontSize(16); doc.setFont('helvetica','bold'); doc.setTextColor(255,255,255)
  doc.text('ArcPay', margin, 14)
  doc.setFontSize(9); doc.setFont('helvetica','normal'); doc.setTextColor(180,180,180)
  doc.text('Booking Receipt · Arc Testnet', margin, 20)
  doc.setFillColor(255,200,0); doc.roundedRect(155,8,40,8,2,2,'F')
  doc.setFontSize(8); doc.setFont('helvetica','bold'); doc.setTextColor(80,60,0)
  doc.text('TESTNET ONLY', 157, 13.5)

  y = 35
  doc.setFontSize(16); doc.setFont('helvetica','bold'); doc.setTextColor(17,17,17)
  const bookingLabel = `Booking Receipt · ${receipt.booking_ref || receipt.booking_id}`
  doc.text(bookingLabel, margin, y); y += 10
  doc.setFontSize(28); doc.setFont('helvetica','bold'); doc.setTextColor(39,117,202)
  doc.text(`${receipt.total_amount} USDC`, margin, y); y += 12
  doc.setFontSize(10); doc.setFont('helvetica','normal'); doc.setTextColor(100,100,100)
  doc.text(receipt.created_at || '', margin, y); y += 10
  addDivider()

  addField('Status',          receipt.status)
  addField('Booking Ref',     receipt.booking_ref)
  addField('Description',     receipt.description)
  addDivider()
  addField('Hotel/Merchant',  receipt.merchant_wallet)
  addField('Trading Name',    receipt.merchant_name)
  if (receipt.merchant_legal_name && receipt.merchant_legal_name !== '—') addField('Legal Name',    receipt.merchant_legal_name)
  if (receipt.merchant_country    && receipt.merchant_country    !== '—') addField('Country',       receipt.merchant_country)
  if (receipt.merchant_address    && receipt.merchant_address    !== '—') addField('Reg. Office',   receipt.merchant_address)
  if (receipt.merchant_vat        && receipt.merchant_vat        !== '—') addField('VAT / Co. ID',  receipt.merchant_vat)
  if (receipt.merchant_lei        && receipt.merchant_lei        !== '—') addField('LEI',           receipt.merchant_lei)
  addField('Guest',           receipt.guest_wallet)
  addDivider()
  addField('Total Paid',      `${receipt.total_amount} USDC`)
  addField('Non-refundable',  `${receipt.non_refundable_amount} USDC (${receipt.non_refundable_pct})`)
  addField('Refundable',      `${receipt.refundable_amount} USDC`)
  addField('Cancel Deadline', receipt.cancellation_deadline)
  addField('Check-in Date',   receipt.check_in_date)
  addDivider()
  const txHashFinal = txHashOverride || receipt.create_tx_hash || receipt.transaction_hash
  addField('TX Hash', txHashFinal || '—')
  addField('ArcScan', txHashFinal ? `https://testnet.arcscan.app/tx/${txHashFinal}` : receipt.arcscan_link)
  addField('Network',         receipt.network)
  addField('Contract',        receipt.contract_address)

  y = 270
  doc.setFontSize(8); doc.setFont('helvetica','normal'); doc.setTextColor(150,150,150)
  const disc = doc.splitTextToSize(receipt.disclaimer || '', 170)
  doc.text(disc, margin, y); y += disc.length * 4 + 4
  doc.text(`Generated by ArcPay v0.1 · ${new Date().toISOString()}`, margin, y)
  doc.save(`arcpay_booking_${(receipt.booking_ref || receipt.booking_id || 'booking').replace(/[^a-zA-Z0-9-_]/g,'_')}.pdf`)
}


// ── Cancel PDF ────────────────────────────────────────────────────────────────
export function downloadCancelBookingPDF(receipt, cancelHash) {
  if (typeof window === 'undefined' || !window.jspdf) { alert('PDF not available.'); return }
  const { jsPDF } = window.jspdf
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const margin = 20; let y = margin

  const addField = (key, value) => {
    doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(100,100,100)
    doc.text(key, margin, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(17,17,17)
    const lines = doc.splitTextToSize(value || '—', 130)
    doc.text(lines, 70, y); y += Math.max(lines.length * 5, 7)
  }
  const addDivider = () => { doc.setDrawColor(220,220,220); doc.line(margin, y, 190, y); y += 5 }

  doc.setFillColor(17,17,17); doc.rect(0,0,210,25,'F')
  doc.setFontSize(16); doc.setFont('helvetica','bold'); doc.setTextColor(255,255,255)
  doc.text('ArcPay', margin, 14)
  doc.setFontSize(9); doc.setFont('helvetica','normal'); doc.setTextColor(180,180,180)
  doc.text('Booking Cancelled · Arc Testnet', margin, 20)
  doc.setFillColor(255,200,0); doc.roundedRect(155,8,40,8,2,2,'F')
  doc.setFontSize(8); doc.setFont('helvetica','bold'); doc.setTextColor(80,60,0)
  doc.text('TESTNET ONLY', 157, 13.5)
  y = 35

  doc.setFontSize(14); doc.setFont('helvetica','bold'); doc.setTextColor(17,17,17)
  doc.text(`Booking Cancelled · ${receipt.booking_ref || receipt.receipt_id}`, margin, y); y += 8
  doc.setFontSize(22); doc.setFont('helvetica','bold'); doc.setTextColor(240,80,80)
  doc.text(`${receipt.refundable_amount} USDC refunded`, margin, y); y += 10
  addDivider()

  addField('Event',         'Booking Cancelled Before Deadline')
  addField('Booking Ref',   receipt.booking_ref || '—')
  addField('Guest',         receipt.guest_wallet || '—')
  addField('Hotel',         receipt.merchant_wallet || '—')
  addField('Refunded',      `${receipt.refundable_amount} USDC`)
  addField('Non-refundable', `${receipt.non_refundable_amount} USDC (retained by hotel)`)
  addDivider()
  addField('Network',       'Arc Testnet · Chain ID 5042002')
  if (cancelHash) {
    addField('TX Hash',     cancelHash)
    addField('ArcScan',     `https://testnet.arcscan.app/tx/${cancelHash}`)
  }
  addField('Booking URL',   receipt.booking_url || '')

  doc.setFontSize(8); doc.setFont('helvetica','normal'); doc.setTextColor(150,150,150)
  doc.text('TESTNET ONLY. Testnet tokens have no real economic value.', margin, 272)
  doc.text(`Generated by ArcPay v0.1 · ${new Date().toISOString()}`, margin, 277)
  doc.save(`arcpay_cancelled_booking_${(receipt.booking_ref || receipt.receipt_id || 'booking').replace(/[^a-zA-Z0-9-_]/g,'_')}.pdf`)
}

// ── Release PDF ───────────────────────────────────────────────────────────────
export function downloadReleaseBookingPDF(receipt, releaseHash) {
  if (typeof window === 'undefined' || !window.jspdf) { alert('PDF not available.'); return }
  const { jsPDF } = window.jspdf
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const margin = 20; let y = margin

  const addField = (key, value) => {
    doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(100,100,100)
    doc.text(key, margin, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(17,17,17)
    const lines = doc.splitTextToSize(value || '—', 130)
    doc.text(lines, 70, y); y += Math.max(lines.length * 5, 7)
  }
  const addDivider = () => { doc.setDrawColor(220,220,220); doc.line(margin, y, 190, y); y += 5 }

  doc.setFillColor(17,17,17); doc.rect(0,0,210,25,'F')
  doc.setFontSize(16); doc.setFont('helvetica','bold'); doc.setTextColor(255,255,255)
  doc.text('ArcPay', margin, 14)
  doc.setFontSize(9); doc.setFont('helvetica','normal'); doc.setTextColor(180,180,180)
  doc.text('Escrow Released to Hotel · Arc Testnet', margin, 20)
  doc.setFillColor(255,200,0); doc.roundedRect(155,8,40,8,2,2,'F')
  doc.setFontSize(8); doc.setFont('helvetica','bold'); doc.setTextColor(80,60,0)
  doc.text('TESTNET ONLY', 157, 13.5)
  y = 35

  doc.setFontSize(14); doc.setFont('helvetica','bold'); doc.setTextColor(17,17,17)
  doc.text(`Escrow Released · ${receipt.booking_ref || receipt.receipt_id}`, margin, y); y += 8
  doc.setFontSize(22); doc.setFont('helvetica','bold'); doc.setTextColor(39,117,202)
  doc.text(`${receipt.refundable_amount} USDC released`, margin, y); y += 10
  addDivider()

  addField('Event',         'Escrow Released to Hotel After Deadline')
  addField('Booking Ref',   receipt.booking_ref || '—')
  addField('Guest',         receipt.guest_wallet || '—')
  addField('Hotel',         receipt.merchant_wallet || '—')
  addField('Released',      `${receipt.refundable_amount} USDC`)
  addField('Non-refundable', `${receipt.non_refundable_amount} USDC (already with hotel)`)
  addField('Total Hotel',   `${receipt.total_amount} USDC`)
  addDivider()
  addField('Network',       'Arc Testnet · Chain ID 5042002')
  if (releaseHash) {
    addField('TX Hash',     releaseHash)
    addField('ArcScan',     `https://testnet.arcscan.app/tx/${releaseHash}`)
  }
  addField('Booking URL',   receipt.booking_url || '')

  doc.setFontSize(8); doc.setFont('helvetica','normal'); doc.setTextColor(150,150,150)
  doc.text('TESTNET ONLY. Testnet tokens have no real economic value.', margin, 272)
  doc.text(`Generated by ArcPay v0.1 · ${new Date().toISOString()}`, margin, 277)
  doc.save(`arcpay_released_booking_${(receipt.booking_ref || receipt.receipt_id || 'booking').replace(/[^a-zA-Z0-9-_]/g,'_')}.pdf`)
}

// ── Full booking PDF (all events) ─────────────────────────────────────────────
export function downloadFullBookingPDF(receipt, events = []) {
  if (typeof window === 'undefined' || !window.jspdf) { alert('PDF not available.'); return }
  const { jsPDF } = window.jspdf
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const margin = 20; let y = margin

  const addField = (key, value) => {
    doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(100,100,100)
    doc.text(key, margin, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(17,17,17)
    const lines = doc.splitTextToSize(String(value || '—'), 130)
    doc.text(lines, 70, y); y += Math.max(lines.length * 5, 7)
  }
  const addDivider = () => { doc.setDrawColor(220,220,220); doc.line(margin, y, 190, y); y += 5 }

  doc.setFillColor(17,17,17); doc.rect(0,0,210,25,'F')
  doc.setFontSize(16); doc.setFont('helvetica','bold'); doc.setTextColor(255,255,255)
  doc.text('ArcPay', margin, 14)
  doc.setFontSize(9); doc.setFont('helvetica','normal'); doc.setTextColor(180,180,180)
  doc.text('Hotel Booking Receipt + Event History · Arc Testnet', margin, 20)
  doc.setFillColor(255,200,0); doc.roundedRect(155,8,40,8,2,2,'F')
  doc.setFontSize(8); doc.setFont('helvetica','bold'); doc.setTextColor(80,60,0)
  doc.text('TESTNET ONLY', 157, 13.5)
  y = 35

  doc.setFontSize(14); doc.setFont('helvetica','bold'); doc.setTextColor(17,17,17)
  doc.text(`Hotel Booking · ${receipt.booking_ref || receipt.receipt_id}`, margin, y); y += 8
  doc.setFontSize(26); doc.setFont('helvetica','bold'); doc.setTextColor(39,117,202)
  doc.text(`${receipt.total_amount} USDC`, margin, y); y += 10
  addDivider()

  // Booking details
  addField('Booking Ref',    receipt.booking_ref || '—')
  addField('Guest',          receipt.guest_wallet || '—')
  addField('Hotel',          receipt.merchant_wallet || '—')
  addField('Non-refundable', `${receipt.non_refundable_amount} USDC`)
  addField('Refundable',     `${receipt.refundable_amount} USDC`)
  addField('Cancel deadline', receipt.cancellation_deadline || '—')
  addField('Check-in',       receipt.check_in_date || '—')
  addField('Network',        'Arc Testnet · Chain ID 5042002')
  addDivider()

  // Event history
  doc.setFontSize(10); doc.setFont('helvetica','bold'); doc.setTextColor(39,117,202)
  doc.text(`Event History (${events.length} event${events.length !== 1 ? 's' : ''})`, margin, y); y += 7

  events.forEach((ev, i) => {
    if (y > 260) { doc.addPage(); y = 20 }
    doc.setFillColor(245,245,245); doc.roundedRect(margin, y-4, 170, ev.txHash ? 20 : 12, 2,2,'F')
    doc.setFontSize(9); doc.setFont('helvetica','bold'); doc.setTextColor(17,17,17)
    doc.text(`${i+1}. ${ev.label}`, margin+3, y+1)
    if (ev.timestamp) {
      doc.setFont('helvetica','normal'); doc.setTextColor(100,100,100)
      doc.text(ev.timestamp, 140, y+1)
    }
    y += 7
    if (ev.detail) {
      doc.setFontSize(8); doc.setFont('helvetica','normal'); doc.setTextColor(80,80,80)
      const dl = doc.splitTextToSize(ev.detail, 162)
      doc.text(dl, margin+3, y); y += dl.length * 4 + 1
    }
    if (ev.txHash) {
      doc.setFontSize(7.5); doc.setFont('helvetica','normal'); doc.setTextColor(39,117,202)
      const tl = doc.splitTextToSize(`TX: ${ev.txHash}`, 162)
      doc.text(tl, margin+3, y); y += tl.length * 4 + 1
      const al = doc.splitTextToSize(`ArcScan: https://testnet.arcscan.app/tx/${ev.txHash}`, 162)
      doc.text(al, margin+3, y); y += al.length * 4 + 1
    }
    y += 4
  })

  addDivider()
  addField('Booking URL', receipt.booking_url || '')
  doc.setFontSize(8); doc.setFont('helvetica','normal'); doc.setTextColor(150,150,150)
  doc.text('TESTNET ONLY. Testnet tokens have no real economic value.', margin, 272)
  doc.text(`Generated by ArcPay v0.1 · ${new Date().toISOString()}`, margin, 277)
  doc.save(`arcpay_full_booking_${(receipt.booking_ref || receipt.receipt_id || 'booking').replace(/[^a-zA-Z0-9-_]/g,'_')}.pdf`)
}
