export function downloadBookingPDF(receipt) {
  if (typeof window === 'undefined' || !window.jspdf) {
    alert('PDF not available. Try JSON download.')
    return
  }
  const { jsPDF } = window.jspdf
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const margin = 20
  let y = margin

  const addField = (key, value) => {
    doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(100,100,100)
    doc.text(key, margin, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(17,17,17)
    const lines = doc.splitTextToSize(value || '—', 130)
    doc.text(lines, 70, y)
    y += Math.max(lines.length * 5, 7)
  }
  const addDivider = () => {
    doc.setDrawColor(220,220,220); doc.line(margin, y, 190, y); y += 5
  }

  // Header
  doc.setFillColor(17,17,17); doc.rect(0,0,210,25,'F')
  doc.setFontSize(16); doc.setFont('helvetica','bold'); doc.setTextColor(255,255,255)
  doc.text('ArcPay', margin, 14)
  doc.setFontSize(9); doc.setFont('helvetica','normal'); doc.setTextColor(180,180,180)
  doc.text('Booking Receipt · Arc Testnet', margin, 20)
  doc.setFillColor(255,200,0); doc.roundedRect(155,8,40,8,2,2,'F')
  doc.setFontSize(8); doc.setFont('helvetica','bold'); doc.setTextColor(80,60,0)
  doc.text('TESTNET ONLY', 157, 13.5)

  y = 35
  doc.setFontSize(16); doc.setFont('helvetica','bold'); doc.setTextColor(17,17,17)
  const bookingLabel = `Booking Receipt · ${receipt.booking_ref || receipt.booking_id}`
  doc.text(bookingLabel, margin, y); y += 10
  doc.setFontSize(28); doc.setFont('helvetica','bold'); doc.setTextColor(39,117,202)
  doc.text(`${receipt.total_amount} USDC`, margin, y); y += 12
  doc.setFontSize(10); doc.setFont('helvetica','normal'); doc.setTextColor(100,100,100)
  doc.text(receipt.created_at || '', margin, y); y += 10
  addDivider()

  addField('Status',          receipt.status)
  addField('Booking Ref',     receipt.booking_ref)
  addField('Description',     receipt.description)
  addDivider()
  addField('Hotel/Merchant',  receipt.merchant_wallet)
  addField('Trading Name',    receipt.merchant_name)
  if (receipt.merchant_legal_name && receipt.merchant_legal_name !== '—') addField('Legal Name',    receipt.merchant_legal_name)
  if (receipt.merchant_country    && receipt.merchant_country    !== '—') addField('Country',       receipt.merchant_country)
  if (receipt.merchant_address    && receipt.merchant_address    !== '—') addField('Reg. Office',   receipt.merchant_address)
  if (receipt.merchant_vat        && receipt.merchant_vat        !== '—') addField('VAT / Co. ID',  receipt.merchant_vat)
  if (receipt.merchant_lei        && receipt.merchant_lei        !== '—') addField('LEI',           receipt.merchant_lei)
  addField('Guest',           receipt.guest_wallet)
  addDivider()
  addField('Total Paid',      `${receipt.total_amount} USDC`)
  addField('Non-refundable',  `${receipt.non_refundable_amount} USDC (${receipt.non_refundable_pct})`)
  addField('Refundable',      `${receipt.refundable_amount} USDC`)
  addField('Cancel Deadline', receipt.cancellation_deadline)
  addField('Check-in Date',   receipt.check_in_date)
  addDivider()
  addField('TX Hash',         receipt.transaction_hash || 'See ArcScan')
  addField('ArcScan',         receipt.arcscan_link)
  addField('Network',         receipt.network)
  addField('Contract',        receipt.contract_address)

  y = 270
  doc.setFontSize(8); doc.setFont('helvetica','normal'); doc.setTextColor(150,150,150)
  const disc = doc.splitTextToSize(receipt.disclaimer || '', 170)
  doc.text(disc, margin, y); y += disc.length * 4 + 4
  doc.text(`Generated by ArcPay v0.1 · ${new Date().toISOString()}`, margin, y)
  doc.save(`arcpay_booking_${(receipt.booking_ref || receipt.booking_id || 'booking').replace(/[^a-zA-Z0-9-_]/g,'_')}.pdf`)
}
