import { ARCSCAN_BASE, APP_URL } from '../config.js'
import { COMMITMENT_STATUS_LABEL, COMMITMENT_TYPE_LABEL } from './commitment.js'
import { REFUND_STATUS_LABEL } from './refund.js'

function formatTs(unix) {
  if (!unix || unix === 0) return '—'
  return new Date(unix * 1000).toISOString().replace('T', ' ').slice(0, 19) + ' UTC'
}

function makePdfBase() {
  if (typeof window === 'undefined' || !window.jspdf) {
    alert('PDF not available — jsPDF not loaded.')
    return null
  }
  const { jsPDF } = window.jspdf
  const doc    = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const margin = 20

  // Header bar
  doc.setFillColor(17, 17, 17); doc.rect(0, 0, 210, 25, 'F')
  doc.setFontSize(16); doc.setFont('helvetica', 'bold'); doc.setTextColor(255, 255, 255)
  doc.text('ArcPay', margin, 14)
  doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(180, 180, 180)
  doc.text('Luxury Payments · Arc Testnet', margin, 20)
  doc.setFillColor(255, 200, 0); doc.roundedRect(155, 8, 40, 8, 2, 2, 'F')
  doc.setFontSize(8); doc.setFont('helvetica', 'bold'); doc.setTextColor(80, 60, 0)
  doc.text('TESTNET ONLY', 157, 13.5)

  const addField = (key, value, y) => {
    doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(100, 100, 100)
    doc.text(key, margin, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(17, 17, 17)
    const lines = doc.splitTextToSize(String(value || '—'), 130)
    doc.text(lines, 70, y)
    return y + Math.max(lines.length * 5, 7)
  }

  const addDivider = (y) => {
    doc.setDrawColor(220, 220, 220); doc.line(margin, y, 190, y)
    return y + 5
  }

  const addDisclaimer = (y) => {
    doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.setTextColor(150, 150, 150)
    const disc = doc.splitTextToSize(
      'TESTNET ONLY. Testnet tokens have no real economic value. Not a regulated payment service. No custody. No KYC/AML.',
      170
    )
    doc.text(disc, margin, y); y += disc.length * 4 + 4
    doc.text(`Generated by ArcPay v0.1 · ${new Date().toISOString()}`, margin, y)
  }

  return { doc, margin, addField, addDivider, addDisclaimer }
}

// ── Commitment creation PDF ───────────────────────────────────────────────────
export function downloadCommitmentPDF(c, txHash) {
  if (!c) return
  const base = makePdfBase(); if (!base) return
  const { doc, margin, addField, addDivider, addDisclaimer } = base
  let y = 35

  doc.setFontSize(14); doc.setFont('helvetica', 'bold'); doc.setTextColor(17, 17, 17)
  doc.text(`${COMMITMENT_TYPE_LABEL[c.type] ?? 'Commitment'} · ${c.ref}`, margin, y); y += 8
  doc.setFontSize(26); doc.setFont('helvetica', 'bold'); doc.setTextColor(39, 117, 202)
  doc.text(`${c.totalAmount} USDC`, margin, y); y += 10
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 100, 100)
  doc.text(`Created: ${formatTs(c.createdAt)}`, margin, y); y += 8
  y = addDivider(y)

  y = addField('Event',        'Commitment Created', y)
  y = addField('Status',       COMMITMENT_STATUS_LABEL[c.status] ?? String(c.status), y)
  y = addField('Type',         COMMITMENT_TYPE_LABEL[c.type] ?? String(c.type), y)
  y = addField('Ref',          c.ref, y)
  if (c.description) y = addField('Description', c.description, y)
  y = addDivider(y)

  y = addField('Merchant',     c.merchant, y)
  y = addField('Customer',     c.customer, y)
  y = addDivider(y)

  y = addField('Total Amount', `${c.totalAmount} USDC`, y)
  if (c.type === 0) {
    y = addField('Due Date',   formatTs(c.dueDate), y)
    y = addField('Deadline',   formatTs(c.deadline), y)
  } else {
    y = addField('Tranches',   `${c.trancheAmounts.length} tranches`, y)
    c.trancheAmounts.forEach((amt, i) => {
      y = addField(`Tranche ${i + 1}`, `${amt} USDC · Due: ${formatTs(c.trancheDueDates[i])} · Deadline: ${formatTs(c.trancheDeadlines[i])}`, y)
    })
  }
  y = addDivider(y)

  y = addField('Network',      'Arc Testnet · Chain ID 5042002', y)
  if (txHash) {
    y = addField('TX Hash',    txHash, y)
    y = addField('ArcScan',    `${ARCSCAN_BASE}/tx/${txHash}`, y)
  }
  y = addField('Receipt URL',  `${APP_URL}/commitment/${c.commitmentId}`, y)

  addDisclaimer(270)
  doc.save(`arcpay_commitment_${(c.ref || c.commitmentId).replace(/[^a-zA-Z0-9-_]/g, '_')}.pdf`)
}

// ── Fulfill / tranche paid PDF ────────────────────────────────────────────────
export function downloadFulfillPDF(c, txHash, trancheIndex = null) {
  if (!c) return
  const base = makePdfBase(); if (!base) return
  const { doc, margin, addField, addDivider, addDisclaimer } = base
  let y = 35

  const isTranche  = trancheIndex !== null
  const eventLabel = isTranche ? `Tranche ${trancheIndex + 1} Paid` : 'Payment Fulfilled'
  const amount     = isTranche ? c.trancheAmounts[trancheIndex] : c.totalAmount

  doc.setFontSize(14); doc.setFont('helvetica', 'bold'); doc.setTextColor(17, 17, 17)
  doc.text(`${eventLabel} · ${c.ref}`, margin, y); y += 8
  doc.setFontSize(26); doc.setFont('helvetica', 'bold'); doc.setTextColor(39, 117, 202)
  doc.text(`${amount} USDC`, margin, y); y += 10
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 100, 100)
  doc.text(`Paid: ${new Date().toISOString().replace('T', ' ').slice(0, 19)} UTC`, margin, y); y += 8
  y = addDivider(y)

  y = addField('Event',        eventLabel, y)
  y = addField('Type',         COMMITMENT_TYPE_LABEL[c.type] ?? String(c.type), y)
  y = addField('Ref',          c.ref, y)
  if (c.description) y = addField('Description', c.description, y)
  y = addDivider(y)

  y = addField('Merchant',     c.merchant, y)
  y = addField('Customer',     c.customer, y)
  y = addDivider(y)

  y = addField('Amount Paid',  `${amount} USDC`, y)
  if (isTranche) {
    y = addField('Tranche',    `${trancheIndex + 1} of ${c.trancheAmounts.length}`, y)
    y = addField('Progress',   `${c.tranchesPaidCount}/${c.trancheAmounts.length} paid`, y)
  }
  y = addDivider(y)

  y = addField('Network',      'Arc Testnet · Chain ID 5042002', y)
  if (txHash) {
    y = addField('TX Hash',    txHash, y)
    y = addField('ArcScan',    `${ARCSCAN_BASE}/tx/${txHash}`, y)
  }
  y = addField('Receipt URL',  `${APP_URL}/commitment/${c.commitmentId}`, y)

  addDisclaimer(270)
  const suffix = isTranche ? `tranche${trancheIndex + 1}` : 'fulfilled'
  doc.save(`arcpay_${suffix}_${(c.ref || c.commitmentId).replace(/[^a-zA-Z0-9-_]/g, '_')}.pdf`)
}

// ── Cancellation PDF ──────────────────────────────────────────────────────────
export function downloadCancelPDF(c, txHash) {
  if (!c) return
  const base = makePdfBase(); if (!base) return
  const { doc, margin, addField, addDivider, addDisclaimer } = base
  let y = 35

  doc.setFontSize(14); doc.setFont('helvetica', 'bold'); doc.setTextColor(17, 17, 17)
  doc.text(`Commitment Cancelled · ${c.ref}`, margin, y); y += 8
  doc.setFontSize(26); doc.setFont('helvetica', 'bold'); doc.setTextColor(240, 80, 80)
  doc.text(`${c.totalAmount} USDC`, margin, y); y += 10
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 100, 100)
  doc.text(`Cancelled: ${new Date().toISOString().replace('T', ' ').slice(0, 19)} UTC`, margin, y); y += 8
  y = addDivider(y)

  y = addField('Event',        'Commitment Cancelled', y)
  y = addField('Type',         COMMITMENT_TYPE_LABEL[c.type] ?? String(c.type), y)
  y = addField('Ref',          c.ref, y)
  y = addDivider(y)
  y = addField('Merchant',     c.merchant, y)
  y = addField('Customer',     c.customer, y)
  y = addDivider(y)
  y = addField('Total Amount', `${c.totalAmount} USDC`, y)
  y = addDivider(y)

  y = addField('Network',      'Arc Testnet · Chain ID 5042002', y)
  if (txHash) {
    y = addField('TX Hash',    txHash, y)
    y = addField('ArcScan',    `${ARCSCAN_BASE}/tx/${txHash}`, y)
  }
  y = addField('Receipt URL',  `${APP_URL}/commitment/${c.commitmentId}`, y)

  addDisclaimer(270)
  doc.save(`arcpay_cancelled_${(c.ref || c.commitmentId).replace(/[^a-zA-Z0-9-_]/g, '_')}.pdf`)
}

// ── Refund event PDF ──────────────────────────────────────────────────────────
export function downloadRefundPDF(c, refund, txHash) {
  if (!c || !refund) return
  const base = makePdfBase(); if (!base) return
  const { doc, margin, addField, addDivider, addDisclaimer } = base
  let y = 35

  const eventLabel = refund.status === 3 ? 'Direct Refund' : `Refund ${REFUND_STATUS_LABEL[refund.status]}`

  doc.setFontSize(14); doc.setFont('helvetica', 'bold'); doc.setTextColor(17, 17, 17)
  doc.text(`${eventLabel} · ${c.ref}`, margin, y); y += 8
  doc.setFontSize(26); doc.setFont('helvetica', 'bold'); doc.setTextColor(39, 117, 202)
  doc.text(`${refund.amount} USDC`, margin, y); y += 10
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 100, 100)
  doc.text(formatTs(refund.processedAt || refund.requestedAt), margin, y); y += 8
  y = addDivider(y)

  y = addField('Event',        eventLabel, y)
  y = addField('Status',       REFUND_STATUS_LABEL[refund.status], y)
  y = addField('Ref',          refund.proofRef || c.ref, y)
  if (refund.reason) y = addField('Reason', refund.reason, y)
  y = addDivider(y)
  y = addField('Merchant',     refund.merchant || c.merchant, y)
  y = addField('Customer',     refund.customer || c.customer, y)
  y = addDivider(y)
  y = addField('Refund Amount', `${refund.amount} USDC`, y)
  y = addField('Requested At',  formatTs(refund.requestedAt), y)
  if (refund.processedAt) y = addField('Processed At', formatTs(refund.processedAt), y)
  y = addDivider(y)

  y = addField('Network',      'Arc Testnet · Chain ID 5042002', y)
  if (txHash) {
    y = addField('TX Hash',    txHash, y)
    y = addField('ArcScan',    `${ARCSCAN_BASE}/tx/${txHash}`, y)
  }
  y = addField('Receipt URL',  `${APP_URL}/commitment/${c.commitmentId}`, y)

  addDisclaimer(270)
  doc.save(`arcpay_refund_${(c.ref || c.commitmentId).replace(/[^a-zA-Z0-9-_]/g, '_')}.pdf`)
}
