import { ARCSCAN_BASE, APP_URL } from '../config.js'
import { COMMITMENT_STATUS_LABEL, COMMITMENT_TYPE_LABEL } from './commitment.js'
import { REFUND_STATUS_LABEL } from './refund.js'

function formatTs(unix) {
  if (!unix || unix === 0) return '—'
  return new Date(unix * 1000).toISOString().replace('T', ' ').slice(0, 19) + ' UTC'
}

function makePdfBase() {
  if (typeof window === 'undefined' || !window.jspdf) {
    alert('PDF not available — jsPDF not loaded.')
    return null
  }
  const { jsPDF } = window.jspdf
  const doc    = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const margin = 20

  // Header bar
  doc.setFillColor(17, 17, 17); doc.rect(0, 0, 210, 25, 'F')
  doc.setFontSize(16); doc.setFont('helvetica', 'bold'); doc.setTextColor(255, 255, 255)
  doc.text('ArcPay', margin, 14)
  doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(180, 180, 180)
  doc.text('Luxury Payments · Arc Testnet', margin, 20)
  doc.setFillColor(255, 200, 0); doc.roundedRect(155, 8, 40, 8, 2, 2, 'F')
  doc.setFontSize(8); doc.setFont('helvetica', 'bold'); doc.setTextColor(80, 60, 0)
  doc.text('TESTNET ONLY', 157, 13.5)

  const addField = (key, value, y) => {
    doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(100, 100, 100)
    doc.text(key, margin, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(17, 17, 17)
    const lines = doc.splitTextToSize(String(value || '—'), 130)
    doc.text(lines, 70, y)
    return y + Math.max(lines.length * 5, 7)
  }

  const addDivider = (y) => {
    doc.setDrawColor(220, 220, 220); doc.line(margin, y, 190, y)
    return y + 5
  }

  const addDisclaimer = (y) => {
    doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.setTextColor(150, 150, 150)
    const disc = doc.splitTextToSize(
      'TESTNET ONLY. Testnet tokens have no real economic value. Not a regulated payment service. No custody.',
      170
    )
    doc.text(disc, margin, y); y += disc.length * 4 + 4
    doc.text(`Generated by ArcPay v0.1 · ${new Date().toISOString()}`, margin, y)
  }

  return { doc, margin, addField, addDivider, addDisclaimer }
}

// ── Commitment creation PDF ───────────────────────────────────────────────────
export function downloadCommitmentPDF(c, txHash, merchantProfile = null) {
  if (!c) return
  const base = makePdfBase(); if (!base) return
  const { doc, margin, addField, addDivider, addDisclaimer } = base
  let y = 35

  doc.setFontSize(14); doc.setFont('helvetica', 'bold'); doc.setTextColor(17, 17, 17)
  doc.text(`${COMMITMENT_TYPE_LABEL[c.type] ?? 'Commitment'} · ${c.ref}`, margin, y); y += 8
  doc.setFontSize(26); doc.setFont('helvetica', 'bold'); doc.setTextColor(39, 117, 202)
  doc.text(`${c.totalAmount} USDC`, margin, y); y += 10
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 100, 100)
  doc.text(`Created: ${formatTs(c.createdAt)}`, margin, y); y += 8
  y = addDivider(y)

  y = addField('Event',        'Commitment Created', y)
  y = addField('Status',       COMMITMENT_STATUS_LABEL[c.status] ?? String(c.status), y)
  y = addField('Type',         COMMITMENT_TYPE_LABEL[c.type] ?? String(c.type), y)
  y = addField('Ref',          c.ref, y)
  if (c.description) y = addField('Description', c.description, y)
  y = addDivider(y)

  if (merchantProfile?.tradingName)     y = addField('Merchant',     merchantProfile.tradingName, y)
  if (merchantProfile?.legalName)       y = addField('Legal Name',   merchantProfile.legalName, y)
  if (merchantProfile?.country)         y = addField('Country',      merchantProfile.country, y)
  if (merchantProfile?.businessAddress) y = addField('Reg. Office',  merchantProfile.businessAddress, y)
  if (merchantProfile?.vatOrCompanyId)  y = addField('VAT / Co. ID', merchantProfile.vatOrCompanyId, y)
  if (merchantProfile?.lei)             y = addField('LEI',          merchantProfile.lei, y)
  y = addField('Merchant wallet', c.merchant, y)
  y = addField('Customer',     c.customer, y)
  y = addDivider(y)

  y = addField('Total Amount', `${c.totalAmount} USDC`, y)
  if (c.type === 0) {
    y = addField('Due Date',   formatTs(c.dueDate), y)
    y = addField('Deadline',   formatTs(c.deadline), y)
  } else {
    y = addField('Tranches',   `${c.trancheAmounts.length} tranches`, y)
    c.trancheAmounts.forEach((amt, i) => {
      y = addField(`Tranche ${i + 1}`, `${amt} USDC · Due: ${formatTs(c.trancheDueDates[i])} · Deadline: ${formatTs(c.trancheDeadlines[i])}`, y)
    })
  }
  y = addDivider(y)

  y = addField('Network',      'Arc Testnet · Chain ID 5042002', y)
  if (txHash) {
    y = addField('TX Hash',    txHash, y)
    y = addField('ArcScan',    `${ARCSCAN_BASE}/tx/${txHash}`, y)
  }
  y = addField('Receipt URL',  `${APP_URL}/commitment/${c.commitmentId}`, y)

  addDisclaimer(270)
  doc.save(`arcpay_commitment_${(c.ref || c.commitmentId).replace(/[^a-zA-Z0-9-_]/g, '_')}.pdf`)
}

// ── Fulfill / tranche paid PDF ────────────────────────────────────────────────
export function downloadFulfillPDF(c, txHash, trancheIndex = null, merchantProfile = null) {
  if (!c) return
  const base = makePdfBase(); if (!base) return
  const { doc, margin, addField, addDivider, addDisclaimer } = base
  let y = 35

  const isTranche  = trancheIndex !== null
  const eventLabel = isTranche ? `Tranche ${trancheIndex + 1} Paid` : 'Payment Fulfilled'
  const amount     = isTranche ? c.trancheAmounts[trancheIndex] : c.totalAmount

  doc.setFontSize(14); doc.setFont('helvetica', 'bold'); doc.setTextColor(17, 17, 17)
  doc.text(`${eventLabel} · ${c.ref}`, margin, y); y += 8
  doc.setFontSize(26); doc.setFont('helvetica', 'bold'); doc.setTextColor(39, 117, 202)
  doc.text(`${amount} USDC`, margin, y); y += 10
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 100, 100)
  doc.text(`Paid: ${new Date().toISOString().replace('T', ' ').slice(0, 19)} UTC`, margin, y); y += 8
  y = addDivider(y)

  y = addField('Event',        eventLabel, y)
  y = addField('Type',         COMMITMENT_TYPE_LABEL[c.type] ?? String(c.type), y)
  y = addField('Ref',          c.ref, y)
  if (c.description) y = addField('Description', c.description, y)
  y = addDivider(y)

  if (merchantProfile?.tradingName)     y = addField('Merchant',     merchantProfile.tradingName, y)
  if (merchantProfile?.legalName)       y = addField('Legal Name',   merchantProfile.legalName, y)
  if (merchantProfile?.country)         y = addField('Country',      merchantProfile.country, y)
  if (merchantProfile?.businessAddress) y = addField('Reg. Office',  merchantProfile.businessAddress, y)
  if (merchantProfile?.vatOrCompanyId)  y = addField('VAT / Co. ID', merchantProfile.vatOrCompanyId, y)
  if (merchantProfile?.lei)             y = addField('LEI',          merchantProfile.lei, y)
  y = addField('Merchant wallet', c.merchant, y)
  y = addField('Customer',     c.customer, y)
  y = addDivider(y)

  y = addField('Amount Paid',  `${amount} USDC`, y)
  if (isTranche) {
    y = addField('Tranche',    `${trancheIndex + 1} of ${c.trancheAmounts.length}`, y)
    y = addField('Progress',   `${c.tranchesPaidCount}/${c.trancheAmounts.length} paid`, y)
  }
  y = addDivider(y)

  y = addField('Network',      'Arc Testnet · Chain ID 5042002', y)
  if (txHash) {
    y = addField('TX Hash',    txHash, y)
    y = addField('ArcScan',    `${ARCSCAN_BASE}/tx/${txHash}`, y)
  }
  y = addField('Receipt URL',  `${APP_URL}/commitment/${c.commitmentId}`, y)

  addDisclaimer(270)
  const suffix = isTranche ? `tranche${trancheIndex + 1}` : 'fulfilled'
  doc.save(`arcpay_${suffix}_${(c.ref || c.commitmentId).replace(/[^a-zA-Z0-9-_]/g, '_')}.pdf`)
}

// ── Cancellation PDF ──────────────────────────────────────────────────────────
export function downloadCancelPDF(c, txHash, merchantProfile = null) {
  if (!c) return
  const base = makePdfBase(); if (!base) return
  const { doc, margin, addField, addDivider, addDisclaimer } = base
  let y = 35

  doc.setFontSize(14); doc.setFont('helvetica', 'bold'); doc.setTextColor(17, 17, 17)
  doc.text(`Commitment Cancelled · ${c.ref}`, margin, y); y += 8
  doc.setFontSize(26); doc.setFont('helvetica', 'bold'); doc.setTextColor(240, 80, 80)
  doc.text(`${c.totalAmount} USDC`, margin, y); y += 10
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 100, 100)
  doc.text(`Cancelled: ${new Date().toISOString().replace('T', ' ').slice(0, 19)} UTC`, margin, y); y += 8
  y = addDivider(y)

  y = addField('Event',        'Commitment Cancelled', y)
  y = addField('Type',         COMMITMENT_TYPE_LABEL[c.type] ?? String(c.type), y)
  y = addField('Ref',          c.ref, y)
  y = addDivider(y)
  if (merchantProfile?.tradingName)     y = addField('Merchant',     merchantProfile.tradingName, y)
  if (merchantProfile?.legalName)       y = addField('Legal Name',   merchantProfile.legalName, y)
  if (merchantProfile?.country)         y = addField('Country',      merchantProfile.country, y)
  if (merchantProfile?.businessAddress) y = addField('Reg. Office',  merchantProfile.businessAddress, y)
  if (merchantProfile?.vatOrCompanyId)  y = addField('VAT / Co. ID', merchantProfile.vatOrCompanyId, y)
  if (merchantProfile?.lei)             y = addField('LEI',          merchantProfile.lei, y)
  y = addField('Merchant wallet', c.merchant, y)
  y = addField('Customer',     c.customer, y)
  y = addDivider(y)
  y = addField('Total Amount', `${c.totalAmount} USDC`, y)
  y = addDivider(y)

  y = addField('Network',      'Arc Testnet · Chain ID 5042002', y)
  if (txHash) {
    y = addField('TX Hash',    txHash, y)
    y = addField('ArcScan',    `${ARCSCAN_BASE}/tx/${txHash}`, y)
  }
  y = addField('Receipt URL',  `${APP_URL}/commitment/${c.commitmentId}`, y)

  addDisclaimer(270)
  doc.save(`arcpay_cancelled_${(c.ref || c.commitmentId).replace(/[^a-zA-Z0-9-_]/g, '_')}.pdf`)
}

// ── Refund event PDF ──────────────────────────────────────────────────────────
export function downloadRefundPDF(c, refund, txHash, merchantProfile = null) {
  if (!c || !refund) return
  const base = makePdfBase(); if (!base) return
  const { doc, margin, addField, addDivider, addDisclaimer } = base
  let y = 35

  const eventLabel = refund.status === 3 ? 'Direct Refund' : `Refund ${REFUND_STATUS_LABEL[refund.status]}`

  doc.setFontSize(14); doc.setFont('helvetica', 'bold'); doc.setTextColor(17, 17, 17)
  doc.text(`${eventLabel} · ${c.ref}`, margin, y); y += 8
  doc.setFontSize(26); doc.setFont('helvetica', 'bold'); doc.setTextColor(39, 117, 202)
  doc.text(`${refund.amount} USDC`, margin, y); y += 10
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 100, 100)
  doc.text(formatTs(refund.processedAt || refund.requestedAt), margin, y); y += 8
  y = addDivider(y)

  y = addField('Event',        eventLabel, y)
  y = addField('Status',       REFUND_STATUS_LABEL[refund.status], y)
  y = addField('Ref',          refund.proofRef || c.ref, y)
  if (refund.reason) y = addField('Reason', refund.reason, y)
  y = addDivider(y)
  y = addField('Merchant',     refund.merchant || c.merchant, y)
  y = addField('Customer',     refund.customer || c.customer, y)
  y = addDivider(y)
  y = addField('Refund Amount', `${refund.amount} USDC`, y)
  y = addField('Requested At',  formatTs(refund.requestedAt), y)
  if (refund.processedAt) y = addField('Processed At', formatTs(refund.processedAt), y)
  y = addDivider(y)

  y = addField('Network',      'Arc Testnet · Chain ID 5042002', y)
  if (txHash) {
    y = addField('TX Hash',    txHash, y)
    y = addField('ArcScan',    `${ARCSCAN_BASE}/tx/${txHash}`, y)
  }
  y = addField('Receipt URL',  `${APP_URL}/commitment/${c.commitmentId}`, y)

  addDisclaimer(270)
  doc.save(`arcpay_refund_${(c.ref || c.commitmentId).replace(/[^a-zA-Z0-9-_]/g, '_')}.pdf`)
}


// ── Full commitment PDF with all events ───────────────────────────────────────
// events: [{ label, txHash, timestamp, detail, note }]
export function downloadFullCommitmentPDF(c, events = [], merchantProfile = null) {
  if (!c) return
  if (typeof window === 'undefined' || !window.jspdf) {
    alert('PDF generation not available.')
    return
  }
  const { jsPDF } = window.jspdf
  const doc    = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const margin = 20
  let y        = margin

  const addField = (key, value) => {
    doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(100, 100, 100)
    doc.text(key, margin, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(17, 17, 17)
    const lines = doc.splitTextToSize(String(value || '—'), 130)
    doc.text(lines, 70, y)
    y += Math.max(lines.length * 5, 7)
  }
  const addDivider = () => {
    doc.setDrawColor(220, 220, 220); doc.line(margin, y, 190, y); y += 5
  }
  const addSectionTitle = (title) => {
    doc.setFontSize(10); doc.setFont('helvetica', 'bold'); doc.setTextColor(39, 117, 202)
    doc.text(title, margin, y); y += 7
  }

  // Header
  doc.setFillColor(17, 17, 17); doc.rect(0, 0, 210, 25, 'F')
  doc.setFontSize(16); doc.setFont('helvetica', 'bold'); doc.setTextColor(255, 255, 255)
  doc.text('ArcPay', margin, 14)
  doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(180, 180, 180)
  doc.text('Commitment Receipt + Event History · Arc Testnet', margin, 20)
  doc.setFillColor(255, 200, 0); doc.roundedRect(155, 8, 40, 8, 2, 2, 'F')
  doc.setFontSize(8); doc.setFont('helvetica', 'bold'); doc.setTextColor(80, 60, 0)
  doc.text('TESTNET ONLY', 157, 13.5)
  y = 35

  // Title
  const typeLabel = c.type === 0 ? 'Delayed Payment' : 'Tranche Payment'
  doc.setFontSize(14); doc.setFont('helvetica', 'bold'); doc.setTextColor(17, 17, 17)
  doc.text(`${typeLabel} · ${c.ref}`, margin, y); y += 8
  doc.setFontSize(26); doc.setFont('helvetica', 'bold'); doc.setTextColor(39, 117, 202)
  doc.text(`${c.totalAmount} USDC`, margin, y); y += 10
  addDivider()

  // Commitment details
  addSectionTitle('Commitment Details')
  addField('Type',         typeLabel)
  addField('Ref',          c.ref)
  if (c.description) addField('Description', c.description)
  addField('Merchant',     c.merchant)
  addField('Customer',     c.customer)
  addField('Total Amount', `${c.totalAmount} USDC`)
  addField('Created',      c.createdAt ? new Date(c.createdAt * 1000).toISOString().replace('T',' ').slice(0,19) + ' UTC' : '—')
  addField('Network',      'Arc Testnet · Chain ID 5042002')
  addDivider()

  // Event history
  addSectionTitle(`Event History (${events.length} event${events.length !== 1 ? 's' : ''})`)
  if (events.length === 0) {
    doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(150, 150, 150)
    doc.text('No events recorded.', margin, y); y += 8
  } else {
    events.forEach((ev, i) => {
      if (y > 260) { doc.addPage(); y = 20 }
      doc.setFillColor(245, 245, 245); doc.roundedRect(margin, y - 4, 170, ev.txHash ? 20 : 12, 2, 2, 'F')
      doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(17, 17, 17)
      doc.text(`${i + 1}. ${ev.label}`, margin + 3, y + 1)
      if (ev.timestamp) {
        doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 100, 100)
        doc.text(ev.timestamp, 140, y + 1)
      }
      y += 7
      if (ev.detail) {
        doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.setTextColor(80, 80, 80)
        const dl = doc.splitTextToSize(ev.detail, 162)
        doc.text(dl, margin + 3, y); y += dl.length * 4 + 1
      }
      if (ev.note) {
        doc.setFontSize(8); doc.setFont('helvetica', 'italic'); doc.setTextColor(100, 100, 150)
        const nl = doc.splitTextToSize(`Note: "${ev.note}"`, 162)
        doc.text(nl, margin + 3, y); y += nl.length * 4 + 1
      }
      if (ev.txHash) {
        doc.setFontSize(7.5); doc.setFont('helvetica', 'normal'); doc.setTextColor(39, 117, 202)
        const tl = doc.splitTextToSize(`TX: ${ev.txHash}`, 162)
        doc.text(tl, margin + 3, y); y += tl.length * 4 + 1
        const al = doc.splitTextToSize(`ArcScan: https://testnet.arcscan.app/tx/${ev.txHash}`, 162)
        doc.text(al, margin + 3, y); y += al.length * 4 + 1
      }
      y += 4
    })
  }
  addDivider()
  addField('Receipt URL', `https://arc-pay-testnet.vercel.app/commitment/${c.commitmentId}`)

  // Footer
  doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.setTextColor(150, 150, 150)
  const disc = doc.splitTextToSize('TESTNET ONLY. Testnet tokens have no real economic value. Not a financial instrument or compliance record.', 170)
  doc.text(disc, margin, 272)
  doc.text(`Generated by ArcPay v0.1 · ${new Date().toISOString()}`, margin, 272 + disc.length * 4 + 2)

  doc.save(`arcpay_full_${(c.ref || c.commitmentId).replace(/[^a-zA-Z0-9-_]/g, '_')}.pdf`)
}
