import { ARCSCAN_BASE, APP_URL } from '../config.js'
import { COMMITMENT_STATUS_LABEL, COMMITMENT_TYPE_LABEL } from './commitment.js'

function formatTs(unix) {
  if (!unix || unix === 0) return '—'
  return new Date(unix * 1000).toISOString().replace('T', ' ').slice(0, 19) + ' UTC'
}

export function downloadCommitmentPDF(c, txHash) {
  if (!c) return
  if (typeof window === 'undefined' || !window.jspdf) {
    alert('PDF not available. Try JSON download.')
    return
  }
  const { jsPDF } = window.jspdf
  const doc    = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const margin = 20
  let y        = margin

  const addField = (key, value) => {
    doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(100, 100, 100)
    doc.text(key, margin, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(17, 17, 17)
    const lines = doc.splitTextToSize(value || '—', 130)
    doc.text(lines, 70, y)
    y += Math.max(lines.length * 5, 7)
  }
  const addDivider = () => {
    doc.setDrawColor(220, 220, 220); doc.line(margin, y, 190, y); y += 5
  }

  // Header
  doc.setFillColor(17, 17, 17); doc.rect(0, 0, 210, 25, 'F')
  doc.setFontSize(16); doc.setFont('helvetica', 'bold'); doc.setTextColor(255, 255, 255)
  doc.text('ArcPay', margin, 14)
  doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(180, 180, 180)
  doc.text(`${COMMITMENT_TYPE_LABEL[c.type] ?? 'Commitment'} Receipt · Arc Testnet`, margin, 20)
  doc.setFillColor(255, 200, 0); doc.roundedRect(155, 8, 40, 8, 2, 2, 'F')
  doc.setFontSize(8); doc.setFont('helvetica', 'bold'); doc.setTextColor(80, 60, 0)
  doc.text('TESTNET ONLY', 157, 13.5)

  y = 35
  doc.setFontSize(16); doc.setFont('helvetica', 'bold'); doc.setTextColor(17, 17, 17)
  doc.text(`${COMMITMENT_TYPE_LABEL[c.type] ?? 'Commitment'} · ${c.ref}`, margin, y); y += 10
  doc.setFontSize(28); doc.setFont('helvetica', 'bold'); doc.setTextColor(39, 117, 202)
  doc.text(`${c.totalAmount} USDC`, margin, y); y += 12
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 100, 100)
  doc.text(formatTs(c.createdAt), margin, y); y += 10
  addDivider()

  addField('Status',      COMMITMENT_STATUS_LABEL[c.status] ?? String(c.status))
  addField('Type',        COMMITMENT_TYPE_LABEL[c.type]   ?? String(c.type))
  addField('Ref',         c.ref)
  if (c.description) addField('Description', c.description)
  addDivider()

  addField('Merchant',    c.merchant)
  addField('Customer',    c.customer)
  addDivider()

  addField('Total Amount', `${c.totalAmount} USDC`)

  if (c.type === 0) {
    // Delayed
    addField('Due Date',  formatTs(c.dueDate))
    addField('Deadline',  formatTs(c.deadline))
    addField('Paid',      c.paid ? 'Yes' : 'No')
  } else {
    // Tranche
    addField('Tranches',  `${c.tranchesPaidCount} / ${c.trancheAmounts.length} paid`)
    c.trancheAmounts.forEach((amt, i) => {
      addField(
        `Tranche ${i + 1}`,
        `${amt} USDC · Due: ${formatTs(c.trancheDueDates[i])} · ${c.tranchePaid[i] ? '✓ Paid' : 'Pending'}`
      )
    })
  }
  addDivider()

  addField('Network',     'Arc Testnet · Chain ID 5042002')
  addField('Created',     formatTs(c.createdAt))
  if (txHash) {
    addField('TX Hash',   txHash)
    addField('ArcScan',   `${ARCSCAN_BASE}/tx/${txHash}`)
  }
  addField('Receipt URL', `${APP_URL}/commitment/${c.commitmentId}`)

  y = 270
  doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.setTextColor(150, 150, 150)
  const disc = doc.splitTextToSize(
    'TESTNET ONLY. Testnet tokens have no real economic value. Not a regulated payment service. No custody. No KYC/AML.',
    170
  )
  doc.text(disc, margin, y); y += disc.length * 4 + 4
  doc.text(`Generated by ArcPay v0.1 · ${new Date().toISOString()}`, margin, y)

  const filename = `arcpay_${c.type === 0 ? 'delayed' : 'tranche'}_${(c.ref || 'commitment').replace(/[^a-zA-Z0-9-_]/g, '_')}.pdf`
  doc.save(filename)
}
