// Client-side PDF generation using jsPDF
// jsPDF is loaded via CDN in index.html

export function downloadReceiptPDF(receipt) {
  // jsPDF loaded globally via CDN
  if (typeof window === 'undefined' || !window.jspdf) {
    alert('PDF generation not available. Please try JSON download.')
    return
  }

  const { jsPDF } = window.jspdf
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const margin = 20
  let y        = margin

  // Helper functions
  const addLine = (text, size = 10, bold = false, color = [17, 17, 17]) => {
    doc.setFontSize(size)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setTextColor(...color)
    doc.text(text, margin, y)
    y += size * 0.5 + 2
  }

  const addField = (key, value) => {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(100, 100, 100)
    doc.text(key, margin, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(17, 17, 17)
    const lines = doc.splitTextToSize(value || '—', 130)
    doc.text(lines, 70, y)
    y += Math.max(lines.length * 5, 7)
  }

  const addDivider = () => {
    doc.setDrawColor(220, 220, 220)
    doc.line(margin, y, 210 - margin, y)
    y += 5
  }

  // Header
  doc.setFillColor(17, 17, 17)
  doc.rect(0, 0, 210, 25, 'F')
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text('ArcPay', margin, 14)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(180, 180, 180)
  doc.text('Payment Receipt · Arc Testnet', margin, 20)

  // Testnet badge
  doc.setFillColor(255, 200, 0)
  doc.roundedRect(155, 8, 40, 8, 2, 2, 'F')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(80, 60, 0)
  doc.text('TESTNET ONLY', 157, 13.5)

  y = 35

  // Receipt ID + amount
  const receiptLabel = receipt.payment_ref
    ? `Payment Receipt · ${receipt.payment_ref}`
    : 'Payment Receipt'
  addLine(receiptLabel, 16, true)
  y += 2
  doc.setFontSize(28)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(39, 117, 202) // USDC blue
  doc.text(`${receipt.amount} ${receipt.token_symbol}`, margin, y)
  y += 12
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text(receipt.timestamp_utc || '', margin, y)
  y += 10

  addDivider()

  // Fields
  addField('Payment Ref',       receipt.payment_ref)
  addField('Purpose',           receipt.purpose_code)
  addField('Description',       receipt.description)
  addDivider()
  addField('Merchant Wallet',   receipt.merchant_wallet)
  addField('Trading Name',      receipt.merchant_name)
  if (receipt.merchant_legal_name && receipt.merchant_legal_name !== '—') addField('Legal Name', receipt.merchant_legal_name)
  if (receipt.merchant_country  && receipt.merchant_country  !== '—') addField('Country',    receipt.merchant_country)
  if (receipt.merchant_address  && receipt.merchant_address  !== '—') addField('Reg. Office', receipt.merchant_address)
  if (receipt.merchant_vat      && receipt.merchant_vat      !== '—') addField('VAT / Co. ID', receipt.merchant_vat)
  if (receipt.merchant_lei      && receipt.merchant_lei      !== '—') addField('LEI',          receipt.merchant_lei)
  addField('Customer Wallet',   receipt.customer_wallet)
  addDivider()
  addField('Token',             `${receipt.token_symbol} (Circle)`)
  addField('Amount',            `${receipt.amount} USDC`)
  addField('Metadata Hash',     receipt.metadata_hash)
  addField('Created Block',     receipt.created_block)
  addDivider()
  addField('TX Hash',           receipt.transaction_hash || 'See ArcScan')
  addField('ArcScan',           receipt.arcscan_link)
  addField('Receipt Page',      receipt.receipt_page)
  addField('Network',           receipt.network)
  addField('Contract',          receipt.contract_address)

  // Footer
  y = 270
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(150, 150, 150)
  const disclaimer = doc.splitTextToSize(receipt.disclaimer || '', 170)
  doc.text(disclaimer, margin, y)
  y += disclaimer.length * 4 + 4
  doc.text(`Generated by ArcPay v0.1 · ${new Date().toISOString()}`, margin, y)

  doc.save(`arcpay_receipt_${(receipt.payment_ref || receipt.receipt_id || 'receipt').replace(/[^a-zA-Z0-9-_]/g,'_')}.pdf`)
}


// ── Full receipt PDF with all events (payment + refund history) ───────────────
export function downloadFullReceiptPDF(receipt, events = []) {
  if (typeof window === 'undefined' || !window.jspdf) {
    alert('PDF generation not available.')
    return
  }
  const { jsPDF } = window.jspdf
  const doc    = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const margin = 20
  let y        = margin

  const addField = (key, value) => {
    doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(100, 100, 100)
    doc.text(key, margin, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(17, 17, 17)
    const lines = doc.splitTextToSize(String(value || '—'), 130)
    doc.text(lines, 70, y)
    y += Math.max(lines.length * 5, 7)
  }
  const addDivider = () => {
    doc.setDrawColor(220, 220, 220); doc.line(margin, y, 190, y); y += 5
  }
  const addSectionTitle = (title) => {
    doc.setFontSize(10); doc.setFont('helvetica', 'bold'); doc.setTextColor(39, 117, 202)
    doc.text(title, margin, y); y += 7
  }

  // Header
  doc.setFillColor(17, 17, 17); doc.rect(0, 0, 210, 25, 'F')
  doc.setFontSize(16); doc.setFont('helvetica', 'bold'); doc.setTextColor(255, 255, 255)
  doc.text('ArcPay', margin, 14)
  doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(180, 180, 180)
  doc.text('Payment Receipt + Event History · Arc Testnet', margin, 20)
  doc.setFillColor(255, 200, 0); doc.roundedRect(155, 8, 40, 8, 2, 2, 'F')
  doc.setFontSize(8); doc.setFont('helvetica', 'bold'); doc.setTextColor(80, 60, 0)
  doc.text('TESTNET ONLY', 157, 13.5)
  y = 35

  // Amount + ref
  doc.setFontSize(14); doc.setFont('helvetica', 'bold'); doc.setTextColor(17, 17, 17)
  doc.text(receipt.payment_ref ? `Payment Receipt · ${receipt.payment_ref}` : 'Payment Receipt', margin, y); y += 8
  doc.setFontSize(26); doc.setFont('helvetica', 'bold'); doc.setTextColor(39, 117, 202)
  doc.text(`${receipt.amount} ${receipt.token_symbol || 'USDC'}`, margin, y); y += 10
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 100, 100)
  doc.text(receipt.timestamp_utc || '', margin, y); y += 8
  addDivider()

  // Payment details
  addSectionTitle('Payment Details')
  addField('Payment Ref',   receipt.payment_ref)
  addField('Purpose',       receipt.purpose_code)
  addField('Description',   receipt.description)
  addDivider()
  addField('Merchant',      receipt.merchant_wallet)
  addField('Trading Name',  receipt.merchant_name)
  addField('Customer',      receipt.customer_wallet)
  addDivider()
  addField('Amount',        `${receipt.amount} USDC`)
  addField('Network',       receipt.network || 'Arc Testnet · Chain ID 5042002')
  addDivider()

  // Event history
  addSectionTitle(`Event History (${events.length} event${events.length !== 1 ? 's' : ''})`)
  if (events.length === 0) {
    doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(150, 150, 150)
    doc.text('No additional events recorded.', margin, y); y += 8
  } else {
    events.forEach((ev, i) => {
      // Event row background
      doc.setFillColor(245, 245, 245); doc.roundedRect(margin, y - 4, 170, ev.txHash ? 18 : 12, 2, 2, 'F')
      doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(17, 17, 17)
      doc.text(`${i + 1}. ${ev.label}`, margin + 3, y + 1)
      if (ev.timestamp) {
        doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 100, 100)
        doc.text(ev.timestamp, 140, y + 1)
      }
      y += 7
      if (ev.txHash) {
        doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.setTextColor(39, 117, 202)
        const txLines = doc.splitTextToSize(`TX: ${ev.txHash}`, 165)
        doc.text(txLines, margin + 3, y)
        y += txLines.length * 4 + 1
        doc.setTextColor(100, 100, 100)
        const arcscan = `https://testnet.arcscan.app/tx/${ev.txHash}`
        const asLines = doc.splitTextToSize(`ArcScan: ${arcscan}`, 165)
        doc.text(asLines, margin + 3, y)
        y += asLines.length * 4 + 1
      }
      if (ev.detail) {
        doc.setFontSize(8); doc.setFont('helvetica', 'italic'); doc.setTextColor(120, 120, 120)
        doc.text(ev.detail, margin + 3, y); y += 5
      }
      y += 4
    })
  }
  addDivider()
  addField('Receipt URL', receipt.receipt_page || window.location.href)

  // Footer
  doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.setTextColor(150, 150, 150)
  const disc = doc.splitTextToSize('TESTNET ONLY. Testnet tokens have no real economic value. Not a financial instrument, tax document, or compliance record.', 170)
  doc.text(disc, margin, 272); doc.text(`Generated by ArcPay v0.1 · ${new Date().toISOString()}`, margin, 272 + disc.length * 4 + 2)

  doc.save(`arcpay_full_receipt_${(receipt.payment_ref || receipt.receipt_id || 'receipt').replace(/[^a-zA-Z0-9-_]/g, '_')}.pdf`)
}
